### ISSUE TITLE
Implement Progress updates to User 

### ISSUE THREAD

**Issue by githengi** [OpenSRP/android-p2p-sync#15]
- [x] Implement Progress updates to User.

- [x] Manifest will use Byte Payload and should not need displaying progress update as it's made of  small messaged .

- [x] Display progress bar  when sending or receiving a stream payload.

- [x] Show summary for transfers e.g  number of Event, Clients, Tasks, Multimedia  transferred. 

- [x] Log the summary in a table that can optionally be synced to server.

**Comment by pld** [comment]
I'd also remove this from MVP, with the understanding that removing it degrades the user experience

**Comment by ekigamba** [comment]
Saving summary progress updates might not be possible for now on the sender side but available on the receiver side. The sender only has the receiver's preferred **name** and **endpoint id** both of which might not be sufficient enough to uniquely identify the receiver when synced to the server.

What exactly did you have in mind when adding this task @githengi ? The usage of the data so that I can initially save all the important data. Syncing might not be done on this issue

**Comment by githengi** [comment]
When handshaking( authentication) I think the sender is able to get more details from the receiver e.g  default team id. Also I think its good to share the logged in username to both parties. The purpose of this task was to save some metrics on what data was shared. 

This could be saved to database or preferably to logs that can be uploaded to fabric dashboard for visualization.

**Comment by ekigamba** [comment]
1. The username to be sent is decided by the host application, which is the logged in username for OpenSRP client core
2. The default team ID is also sent during authorization in OpenSRP client core

Cool, so let me get this right.

You need:
1. Both the sender and receiver to save the entity type, number of records transferred and time

I assumed the transfer records would be used for troubleshooting situations and reason I talk of identifying device. Do you only require general information about the transfer? In that case, I would save the authorization details as JSON and also the general details about data shared.

Either case, we can provide the saving for transfer records as an interface and have both interfaces(Fabric implementation & save to do) for configuration by the host application.

This can just be plugged in on the host application as one of the options, but I need to know what details are of importance here since this determines how much more data I collect on the sender

**Comment by githengi** [comment]
> Both the sender and receiver to save the entity type, number of records transferred and time
Yes and the other party details 

Only  general information about the transfer is required.

The purpose was for troubleshooting and also for visibility about data exchanged on the field. 

For now just log this information using default logging with a different tag from other messages so that it may be possible to easily run analytics if configured on Fabric.

Don't implement the saving interfaces for now.
