### ISSUE TITLE
Disconnect from connection after completing transfer

### ISSUE THREAD

**Issue by githengi** [OpenSRP/android-p2p-sync#16]
After completing transfer of data. Notify user though the [progress update interface](https://github.com/OpenSRP/opensrp-client-p2p/issues/15) that transfer is complete and disconnect from the connection

**Comment by ekigamba** [comment]
I have moved notifying the user through the progress update interface to the specific issue https://github.com/OpenSRP/opensrp-client-p2p/issues/15 since it is not in the MVP.

Therefore this issue will 
- [x] inform the receiving end that the transfer is complete
- [x] disconnect
- [x] implement resetting the connection incase of an error
