### ISSUE TITLE
QR code not working in some instances

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/android-p2p-sync#71]
I've been able to replicate this myself as well. Reading the QR code doesn't seem to work.

This is on the Togo app, production version.
I can share the details of two accounts for testing.

**Comment by ekigamba** [comment]
@cafootitt 
Kindly share the details of the two apps & the device used. 

**Does this happen for all accounts on that device?**
 If yes, kindly connect to internet connection and open PlayStore. The library required for scanning is also provided by Google and is not default on all devices. When PlayStore discovers that it is discovered, it tries to download it or **prioritises it's download when you next connect to internet**. Try and scan after connecting. 

If no, then kindly share the accounts for which the scanning works and the accounts for which this does not work. Also share the device details and version of APK. 😄 Basically any information you used to verify and replicate the issue, so that I can slowly walkthrough the working and figure out what's wrong

**Comment by cafootitt** [comment]
Thanks, Kigamba. Let me get these details for you.

**Comment by cafootitt** [comment]
closing this
